name: Commit Message Check
on: [push, pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set COMMIT_COUNT env var
        run: |
          # Convert the commits to JSON, parse length with jq, and write to GITHUB_ENV
          echo "COMMIT_COUNT=$(echo '${{ toJson(github.event.commits) }}' | jq '. | length')" >> $GITHUB_ENV

      - name: Check commit messages
        shell: bash
        run: |
          # Now we have COMMIT_COUNT in the environment
          echo "Detected $COMMIT_COUNT commits"
          messages=$(git log --format=%B --no-merges HEAD~"$COMMIT_COUNT"..HEAD)
          echo "Commit messages:"
          echo "${messages}"

          # Enforce "updated"
          if ! echo "${messages}" | grep -qi "updated"; then
            echo "Your commit message must contain the word 'updated'."
            exit 1
          fi
